### ISSUE TITLE
Wants to help with the project

### ISSUE THREAD

**Issue by BDVGitHub** [nobelization/panoramax-mobile-app#116]
Hey,

I would like to help with the GitHub project, what are the things I can do?

I also saw that there are 2 "good Issues" but not that weed or someone is already working on this...
https://github.com/nobelization/panoramax-mobile-app/contribute

**Comment by overflorian** [comment]
Hi @BDVGitHub and thanks for your proposal to help.
To be honest, there is a lot to do and I'm not sure what you would prefer to help with.

Regarding the 2 issues you mentioned, I closed them because they refer to some upcoming features that you could help with:
- create a menu to be able to change instance login https://github.com/nobelization/panoramax-mobile-app/issues/51
- https://github.com/nobelization/panoramax-mobile-app/issues/119

The main developer is @OtterWays, she will be happy to help if needed

**Comment by BDVGitHub** [comment]
How can I get in touch with @OtterWays to ask questions?
Is there some kind of guide/tutorial on how to best contribute to the GitHub project?

**Comment by chrisdebian** [comment]
Hi, @BDVGitHub 

I wonder whether it would be a good idea to help, by triaging the [open issues](https://github.com/nobelization/panoramax-mobile-app/issues)? There are currently 39, and it might help to align them to the roadmap for the project, so the dev/s have something to work to, that has been prioritized.

Just an idea.

Cheers,

Chris.

**Comment by BDVGitHub** [comment]
@OtterWays Do you use [GitHub CLI](https://cli.github.com/) or [GitHub desktop](https://github.com/apps/desktop) or something else? Can you send the steps and commands to install the correct dart and docker? Thx

**Comment by BDVGitHub** [comment]
Or @luifr10 @Jean-BaptisteC @Thithip @cquest can any of you answer the above question? Thanks in advance.

**Comment by BDVGitHub** [comment]
Ok
