### ISSUE TITLE
Prioritization of Bugs and Features/ Enhancements

### ISSUE THREAD

**Issue by chrisdebian** [nobelization/panoramax-mobile-app#138]
Hi, all.

I posted something on Mastodon, but the Mastodon client on my phone isn't the easiest thing to navigate! I may have mentioned this elsewhere, but i've had a turbulent couple of months, so forgive me if this sounds familiar.

It would be really good if we can triage some of the bugs/  features backlog, so that we can work out what order to try to produce things. We could go as far as allocating milestones, but that's another thing.

Would the main contributors mind if I had a go at this? Essentially this would ask developers for thoughts on what is most important, and then try to make some order of this. [This](https://github.com/orgs/nobelization/projects/1/views/1) could be useful.

What do you think?

Thanks,

Chris.

**Comment by overflorian** [comment]
Hi, thanks for this proposal. We had a lot of discussion about this, I recently published the current roadmap https://community.openstreetmap.org/t/panoramax-app-for-android/120510/7 and now, we are planning to migrate to Gitlab and to discuss publicly the milestones here https://gitlab.com/panoramax/clients/mobile-app/-/milestones
As you can see, it's empty now, because we have not migrated yet, but it will happen very soon, early 2025. We'll keep you posted!
