### ISSUE TITLE
Shooting screen.

### ISSUE THREAD

**Issue by OtterWays** [nobelization/panoramax-mobile-app#28]
What do you think about our proposals for the picture-taking screen (single view and burst mode)?

<img width="390" alt="Prise d'une photo - raphale" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/c9413e8f-cf9a-43e0-bbab-8dccc7f98468"> <img width="390" alt="Prise d'une photo - seule" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/6716fdcc-748e-47d6-9c0f-5410652dbaf8">

**Important point:** the user will have to put the phone in portrait mode for the photo to be in the right format. 
So we'd like to "lock" the phone in portrait format when the photo is taken (the model will have to be modified to take account of this constraint).

**Comment by OtterWays** [comment]
Here are the new mockups for the camera page
<img width="390" alt="Prise d'une photo - tutoriel (1)" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/d309e234-9ceb-4f5b-a093-4effd2a485ba">
<img width="844" alt="Prise d'une photo - seule" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/daf298bf-80b6-4ac6-b7c5-cf5bd7f31bb6">
<img width="844" alt="Prise d'une photo - raphale" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/5650eb02-8dac-4366-84e9-4ec247e5eb2c">
<img width="844" alt="Prise d'une photo - raphale - prise de vue" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/877a3f6a-8d16-4654-9cf4-db9ee22eda9f">

As burst mode is not implemented yet, this will be done in another issue

**Comment by u4y0u** [comment]
Optionally, in the future, this same screen could control an external camera by triggering the start or stop of capture via a Bluetooth connection as is already done on other applications.
The goal is to avoid taking several smartphones into the field for an image capture sequence:
360 capture via external camera and integrated 2D capture that can be controlled by the same smartphone and a single application.

**Comment by luifr10** [comment]
I wonder if the burst mode is linked to a time interval or a distance interval? Because if the user doesn't move around, is it really relevant to keep taking burst photos ?

**Comment by u4y0u** [comment]
The ideal for burst mode is linked to a distance interval because the goal is mainly to capture terrain images regularly along a path. The only 'fixed' mode that can be interesting is the panorama mode where you can chain together a series of images from a fixed point but with a different angle.
There is, however, a disadvantage when taking photos at a programmed distance interval, which is that this operation is dependent on the quality of the precision of the GPS and the gyroscope of the smartphone.
This is why, sometimes, depending on the terrain where you are located, it is preferable to use burst mode shooting triggered by a simple timer, even if it means manually stopping it when you stop moving.
