### ISSUE TITLE
Photo upload screen:

### ISSUE THREAD

**Issue by OtterWays** [nobelization/panoramax-mobile-app#29]
We think that to optimize the user experience, we should have a counter showing the number of photos taken, and then access the same multiple send screen as for burst mode, so that our users can more easily choose which photos to send.

<img width="390" alt="Envoi de photos - raphale" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/b921c6fc-5fb4-4c36-8f34-b61298859226">
<img width="390" alt="Envoi d'une photo seule" src="https://github.com/nobelization/panoramax-mobile-app/assets/68080267/900c7ee8-8382-463a-b6f3-aed26c911a00">

**Comment by u4y0u** [comment]
It would be interesting to be able to connect an external medium (SD card of 360 cam, drone) to upload the images directly from the app from the field to the instance of your choice among the favorite instances already configured in the preferences of the 'application.

**Comment by OtterWays** [comment]
yes, this is planned for future improvement!

**Comment by u4y0u** [comment]
There is also an interesting point to discuss on this screen.
That of the precision of the localization of the photos.

Indeed I don't think it is good to transfer images whose location is wrong or even absent.

It would therefore be good to specify to the user before transfer that certain photos cannot be processed.
For example, we could superimpose an X or surround the photos that do not meet the criteria with a border of a certain color.

The sending message could be preceded by an explanation if certain photos are defective.

Ideally, the user should be given the possibility of exporting the incriminated photos to offer him the possibility of recreating a correct geotag via external software if he has the possibility (I am thinking of JOSM which is perfectly suited to this task)
This possibility is important, because sometimes the exploration of a place cannot be repeated or is complicated and it is frustrating to have to throw away a correct shot just because the metadata is incorrect even though the photo is very good.
