### ISSUE TITLE
OpenSphericalCamera (OSC) support

### ISSUE THREAD

**Issue by RedAuburn** [nobelization/panoramax-mobile-app#42]
https://developers.google.com/streetview/open-spherical-camera/reference

OSC is the most standardised way of controlling 360 cameras, it'd be great if we could connect a camera to the app for easy uploading.

**Comment by u4y0u** [comment]
The RICOH THETA Z1 camera uses the Open Spherical Camera API via an SSID of the type 'THETA-'ID_camera'.OSC' for example.

But these are often cameras without integrated GPS which have the disadvantage of having a gap between the real position and the measured position already due to the communication delay and the processing of the data via wifi and the possible distance between the smartphone, which acts as GPS, and the remote position of the camera.

The result is often mediocre if you are moving, but on the other hand well suited for shooting in a fixed position or at most for a walker who is walking slowly.

This method should be avoided for vehicle travel because it can introduce position differences of sometimes more than 30 meters between the actual position of the shot and the coordinates recorded in the photo.
If this protocol is integrated, users will therefore have to be warned.

**Comment by RedAuburn** [comment]
> The RICOH THETA Z1 camera uses the Open Spherical Camera API via an SSID of the type 'THETA-'ID_camera'.OSC' for example.
> 
> But these are often cameras without integrated GPS which have the disadvantage of having a gap between the real position and the measured position already due to the communication delay and the processing of the data via wifi and the possible distance between the smartphone, which acts as GPS, and the remote position of the camera.

the usual process is to capture a GPX track while taking photos, then in post-processing get the coordinates from the track based on the time the photo was taken

**Comment by overflorian** [comment]
The Panoramax app vision is to enable people with no extra hardware (such as a 360° camera).
As there are already great software to control GoPro cameras (see https://forum.geocommuns.fr/t/multi-gopro-max-une-photo-360-par-seconde/1694), this won't be implemented.
You have to understand that our developer ressource is very limited so we have to stay focus.

**Comment by RedAuburn** [comment]
that's fair :)
